"""feat: update buildings amenities

Revision ID: 2c14bb9a4895
Revises: a0d563120408
Create Date: 2025-02-16 15:40:55.873357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "2c14bb9a4895"
down_revision: Union[str, None] = "a0d563120408"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "amenities",
        "geometry",
        existing_type=Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        type_=Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
        ),
        existing_nullable=False,
    )
    op.add_column("buildings", sa.Column("amenity", sa.UUID(), nullable=True))
    op.add_column(
        "buildings",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column("buildings", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.alter_column(
        "buildings",
        "geometry",
        existing_type=Geometry(
            geometry_type="POLYGON",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        type_=Geometry(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
        ),
        existing_nullable=False,
    )
    op.create_foreign_key(None, "buildings", "amenities", ["amenity"], ["id"])
    op.create_foreign_key(None, "buildings", "users", ["updated_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "buildings", type_="foreignkey")
    op.drop_constraint(None, "buildings", type_="foreignkey")
    op.alter_column(
        "buildings",
        "geometry",
        existing_type=Geometry(
            geometry_type="POLYGON",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
        ),
        type_=Geometry(
            geometry_type="POLYGON",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    op.drop_column("buildings", "updated_by")
    op.drop_column("buildings", "updated_at")
    op.drop_column("buildings", "amenity")
    op.alter_column(
        "amenities",
        "geometry",
        existing_type=Geometry(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
        ),
        type_=Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
